### ISSUE TITLE
ENOENT: no such file or directory, stat '/home/shintaro/Desktop/projects/github/frontend/node_modules/next-pkg/lib/server.js'

### ISSUE THREAD

**Issue by ShintaroNippon** [fmiras/next-pkg#73]
hello...
I'm using this boiler plalate

sudo npm run dist

> next-express-bootstrap-boilerplate@0.1.1 dist /home/shintaro/Desktop/projects/github/frontend
> next-pkg

✖ Error copying temporary files: Error: ENOENT: no such file or directory, stat '/home/shintaro/Desktop/projects/github/frontend/node_modules/next-pkg/lib/server.js'
(node:12322) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/home/shintaro/Desktop/projects/github/frontend/node_modules/next-pkg/lib/server.js'
(node:12322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12322) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AienTech** [comment]
still getting this error, have fixed it?

**Comment by hatembentayeb** [comment]
I have the same error here, any fixes
