### ISSUE TITLE
Can't resolve '@babel/runtime-corejs2/core-js/array/is-array' in '/snapshot/frontend/node_modules/next-server/dist/lib'

### ISSUE THREAD

**Issue by ShintaroNippon** [fmiras/next-pkg#74]
Hi there, have you had an idea of this?

https://github.com/zeit/pkg/issues/694

Thanks
Carlos Vieira

**Comment by fmiras** [comment]
Please don't bring pkg issues from their repo

**Comment by ShintaroNippon** [comment]
sorry you are right
